"use client";
import {useState} from "react";
import Link from "next/link";
import {Container} from "@/components/ui/Container";
import {Motion3D} from "./Motion3D";
import {MotionFigure} from "./MotionFigure";
import styles from "./MotionSystem.module.css";
type Example={file:string;title:string;copy:string};
const examples:Record<string,Example[]>={
 "d2c-growth":[{file:"pixelcliq-growth-loop",title:"One connected customer journey",copy:"Acquisition, your store, follow-ups and repeat purchase work together. We look at the whole journey before choosing where to focus."},{file:"pixelcliq-cac-reduction",title:"Understand acquisition cost",copy:"Connect creative testing and conversion improvements to the cost of winning a new customer."},{file:"pixelcliq-ltv-retention",title:"Plan beyond the first order",copy:"Build useful post-purchase journeys around replenishment, loyalty and the products your customers buy next."}],
 creative:[{file:"pixelcliq-creative-testing",title:"Test ideas with a purpose",copy:"Compare hooks, formats and offers. Keep a clear record of what to learn from each creative test."},{file:"loop-03-create-connection",title:"Carry the story through",copy:"Connect the ad, product page and follow-up so the experience feels consistent from first click to checkout."}],
 shopify:[{file:"pixelcliq-cro-product-page",title:"Make buying feel easier",copy:"Bring product detail, useful proof, delivery information and a clear next step into the buying journey."},{file:"pixelcliq-cart-recovery-journey",title:"Continue the conversation",copy:"Plan a considered sequence after checkout is abandoned, with sensible timing and clear opt-outs."},{file:"pixelcliq-rto-reduction",title:"Reduce delivery friction",copy:"Use address checks, order confirmations and fulfilment signals to improve the COD journey."}],
 automation:[{file:"pixelcliq-whatsapp-ai-agent",title:"Give every enquiry a next step",copy:"Connect product questions, order information and human handover in one conversation."},{file:"pixelcliq-whatsapp-retention",title:"Stay useful after purchase",copy:"Timely product tips and replenishment reminders keep the conversation relevant."},{file:"pixelcliq-rto-call-verification",title:"Confirm before dispatch",copy:"Build order-verification workflows around customer consent, address checks and clear delivery information."},{file:"pixelcliq-cart-recovery",title:"Reconnect with interested shoppers",copy:"Coordinate email and messaging around the customer's last action."}],
 data:[{file:"pixelcliq-weekly-report",title:"Turn a report into a decision",copy:"Bring the week's signals, learnings and next actions together in a shared reporting rhythm."},{file:"pixelcliq-profit-waterfall",title:"See the margin behind revenue",copy:"Look beyond sales to advertising, delivery, returns and the cost of the product."},{file:"pixelcliq-ltv-calculator",title:"Know what retention changes",copy:"Explore how order value, frequency, margin and customer lifetime affect your acquisition decisions."},{file:"pixelcliq-customer-segments",title:"Treat different customers differently",copy:"Use purchase behaviour to shape useful follow-ups and avoid sending everyone the same message."}],
 seo:[{file:"loop-01-discover-clarity",title:"Start with the right questions",copy:"Understand audience intent, your offer and the gaps in the journey before deciding what content to create."},{file:"loop-02-strategise-direction",title:"Build a clear search roadmap",copy:"Turn the audit into priorities, ownership and a practical sequence of work."}],
 performance:[{file:"pixelcliq-roas-gauge",title:"Connect spend to the full journey",copy:"Review creative, offers, conversion and retention together when interpreting return on ad spend."},{file:"pixelcliq-cac-reduction",title:"Find the cost of the next customer",copy:"Separate acquisition signals from the wider costs of running and fulfilling the business."}],
 "web-development":[{file:"pixelcliq-cro-product-page",title:"Give every page one job",copy:"Plan the headline, proof and call to action around the single thing a visitor should do next."},{file:"loop-04-launch-momentum",title:"Launch, then keep improving",copy:"Watch how visitors use the page after launch and refine the sections that slow them down."}],
 "lead-generation":[{file:"pixelcliq-whatsapp-ai-agent",title:"Reply in minutes, not days",copy:"New enquiries get an instant, useful reply and a clear route to booking a call with your team."},{file:"pixelcliq-customer-segments",title:"Separate curious from ready",copy:"Qualifying questions and follow-up paths treat a browsing visitor differently from someone ready to buy."}],
 branding:[{file:"loop-03-create-connection",title:"One look, every touchpoint",copy:"Carry the same colours, type and tone from the ad to the page to the parcel on the doorstep."},{file:"pixelcliq-creative-testing",title:"Design that holds up in testing",copy:"Build brand templates flexible enough to test new hooks and formats without losing recognition."}],
 "social-media":[{file:"pixelcliq-creative-testing",title:"Give content a learning loop",copy:"Use clear hypotheses to test different stories and formats, then bring the learning into the next content cycle."},{file:"pixelcliq-customer-segments",title:"Speak to the right audience",copy:"Build content and follow-up around where people are in their relationship with the brand."}]
};
export function MotionExplainer({service="d2c-growth"}:{service?:string}){const list=examples[service]??examples["d2c-growth"]!;const [active,setActive]=useState(0);const item=list[active]??list[0]!;return <section className={styles.section}><Container><div className={styles.heading}><div><p>HOW THE SYSTEM WORKS</p><h2>See the thinking.<br/><span>Follow the motion.</span></h2></div><p>A closer look at the journeys we build. Example figures show the mechanics, not client results.</p></div><div className={styles.layout}><div className={styles.copy}><div className={styles.choices} aria-label="Choose a workflow">{list.map((e,i)=><button key={e.file} aria-pressed={active===i} onClick={()=>setActive(i)}><span>0{i+1}</span>{e.title}<span>↗</span></button>)}</div><p>{item.copy}</p><Link href="/contact">Build this into your growth plan ↗</Link></div><MotionFigure key={item.file} file={item.file} title={item.title} dark={item.file.startsWith("loop-")}/></div>{service==="creative"||service==="shopify"?<Motion3D/>:service==="performance"?<Motion3D scene="rocket"/>:null}</Container></section>}
