import type { Metadata } from "next";
import { buildMetadata } from "@/lib/seo";
import { Container } from "@/components/ui/Container";
import { PageHero } from "@/components/sections/PageHero";
import { CrossedBands } from "@/components/sections/PortfolioStage";
import { GrowthProcess } from "@/components/sections/GrowthVisuals";
import { aboutPage } from "@/content/home";
import styles from "@/components/services/StudioPages.module.css";
export const metadata:Metadata=buildMetadata({title:"About Pixelcliq",description:"Pixelcliq Media is an independent creative and growth studio. One team for ads, creative, Shopify and WhatsApp automation, from first scroll to repeat order.",path:"/about",eyebrow:"About"});
export default function AboutPage(){return <><PageHero id="about-heading" eyebrow="THE THINKING BEHIND THE WORK" headlineLines={["ONE TEAM.","THE WHOLE PICTURE."]} support={aboutPage.support}/><section className={styles.section}><Container><div className={styles.sectionHead}><div><p className={styles.label}>WHY PIXELCLIQ</p><h2>GREAT BRANDS<br/><em>NEED CONNECTION.</em></h2></div><p className={styles.copy}>The idea, the ad, the store and the follow-up all shape the same customer journey. We bring them into one conversation, so your brand can move with a clear direction.</p></div><div className={styles.deliverables}>{aboutPage.principles.map((item,i)=><article key={item.title} className={styles.deliverable}><span className={styles.number}>0{i+1}</span><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></Container></section><CrossedBands/><section className={`${styles.section} ${styles.dark}`} data-tone="inverse"><Container><div className={styles.sectionHead}><div><p className={styles.label}>HOW WE WORK</p><h2>THINK. MAKE.<br/><em>LEARN. REPEAT.</em></h2></div><p className={styles.copy}>Clear priorities. Connected execution. A practical rhythm for doing the work and improving it.</p></div><GrowthProcess/></Container></section><section className={styles.section}><Container className={styles.fitGrid}><div><p className={styles.label}>WHEREVER YOUR CUSTOMERS ARE.</p><h2>REMOTE BY DESIGN.<br/><em>CLOSE BY HABIT.</em></h2><p className={styles.copy}>{aboutPage.whereBody}</p></div><div className={styles.fitCard}>{aboutPage.facts.map(f=><div key={f.label} className="border-b border-line py-4"><p className={styles.label}>{f.label}</p><p className="mt-2">{f.value}</p></div>)}</div></Container></section></>}
